src/java/com/uniquindio/siviuq/jsf/InvestigadorController.java
package com.uniquindio.siviuq.jsf;

import com.uniquindio.siviuq.entities.Investigador;
import com.uniquindio.siviuq.jsf.util.JsfUtil;
import com.uniquindio.siviuq.jsf.util.PaginationHelper;
import com.uniquindio.siviuq.beans.InvestigadorFacade;
import com.uniquindio.siviuq.entities.Titulo;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import org.primefaces.model.UploadedFile;

@ManagedBean(name = "investigadorController")
@SessionScoped
public class InvestigadorController implements Serializable {

    private Investigador current;
    private DataModel items = null;
    @EJB
    private com.uniquindio.siviuq.beans.InvestigadorFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private UploadedFile file;
    private String mensaje;
    private List<Investigador> listaInvestigadores;
    private Investigador seleccionada;
    private List<Investigador> nuevalistaInvestigadores = new ArrayList();
   
    @ManagedProperty(value="#{tituloController}")
    private TituloController tituloController;
    

    
    
    
   public String cargarInvestigadores(){
       return null;
   }
    
    public String index(){
        return "verInformacionInvestigador.sv";
    }
    
    public List<Titulo> listaTitulos(){
        List<Titulo> li= (List)getSelected().getTituloCollection();
        System.out.println(li.get(0).getNombre());
        String titulos="";
        String coma="  ";
        for(int i=0; i<li.size();i++){
            titulos=coma+titulos;
            coma=" , ";
        }
        
        return null;
    }
    
    
    public InvestigadorController() {
    }

    public Investigador getSelected() {
        if (current == null) {
            current = new Investigador();
            selectedItemIndex = -1;
        }
        return current;
    }

    private InvestigadorFacade getFacade() {
        return ejbFacade;
    }
    
    public void Buscar(){
     
     current=getFacade().find(current.getIdinvestigador()); 
     System.out.println(current.getNombre());
    }
    
    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

   
    
    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Investigador) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Investigador();
        selectedItemIndex = -1;
        return "crearInvestigador.sv";
    }

    public String create() {
       
        try {
            getFacade().create(current);
            setMensaje("Se creo el Investigador");
            
            return prepareCreate();
        } catch (Exception e) {
             setMensaje("Se presento un problema al crear el investigador");
        }
        return null;
    }

    public String prepareEdit() {
        current = (Investigador) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
       System.out.println(current.getIdinvestigador());
        try {
            getFacade().edit(current);
            setMensaje("El investigador se actualizo correctamente");
            current=null;
            return "crearInvestigador.sv";
        } catch (Exception e) {
            setMensaje("Se genero un problema al actualizar el investigador");
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    
    public String remove() {
        Investigador u=getFacade().find(current.getIdinvestigador());
        
        try {
            getFacade().remove(u);
            setMensaje("Investigador Eliminado Exitosamente");
            current=null;
            return "crearInvestigador.sv";
        } catch (Exception e) {
            setMensaje("Error al eliminar el Investigador");
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }
    
    public String destroy() {
        current = (Investigador) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("InvestigadorDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany2(List<Investigador> li) {
        return JsfUtil.getSelectItemsInvestigador(li, false);   
     }
    
    
    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItemsInvestigador(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItemsInvestigador(ejbFacade.findAll(), true);
    }
    
    public SelectItem[] getItemsAvailableSelectOneTitulo() {
        
        return JsfUtil.getSelectItemsTitulo((List)getSelected().getTituloCollection(), true);
    }

    @FacesConverter(forClass = Investigador.class)
    public static class InvestigadorControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            InvestigadorController controller = (InvestigadorController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "investigadorController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Investigador) {
                Investigador o = (Investigador) object;
                return getStringKey(o.getIdinvestigador());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Investigador.class.getName());
            }
        }

    }

    public Investigador getCurrent() {
        return current;
    }

    public void setCurrent(Investigador current) {
        this.current = current;
    }

    public InvestigadorFacade getEjbFacade() {

web/investigador/editarInvestigador.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../WEB-INF/TemplateSV.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    
    <ui:define name="menuLeft">
       
           <h:form id="menu">
                           <p:menu >
                            <p:submenu label="#{props['investigador']}" >
                                <p:menuitem value="#{props['admin.cinicio']}" url="./../investigador.sv" />
                                <p:menuitem value="#{props['inv.lbl.menu1']}" url="./editarInvestigador.sv"  />
                                <p:menuitem value="#{props['inv.lbl.menu2']}" url="./verInformacionInvestigador.sv"/>
                                <p:menuitem value="#{props['inv.lbl.menu3']}" url="./mostrarConvocatoria.sv"/>
                                <p:menuitem value="#{props['usu.lbl.menu4']}" url="./crearProyecto.sv"/>
                                <p:menuitem value="#{props['admin.salir']}" url="/logout.jsp" />
                            </p:submenu>
                         </p:menu>
               </h:form>
    
    </ui:define>

    <ui:define name="content">
        
        <p:panel id="editarInv" header="#{props['inv.lbl.editar']}"  style="margin-bottom:20px; width: 85%; margin-left: 7%; margin-top: 20px;">
          
           <h:form id="formInvestigador" >
            <center>     
               <p:focus for="txtIdInvestigador"/>
                  <table align="center">
                    <tr>
                        <td style="font-weight: bold; size: 25px; color: blue;" align="right" >#{props['inv.lbl.cedula']} : </td>
                      <td><p:inputText id="txtIdInvestigador"  value="#{usuarioController.usuarioValidado.idinvestigador.idinvestigador}" 
                                       required="true" style="background-color: #FBDCDC ;"
                                        disabled="true"/></td>
                     
                    </tr>
                    
                    <tr>
                      <td style="font-weight: bold; size: 25px; color: blue;" align="right">#{props['inv.lbl.nombre']}: </td>
                      <td><p:inputText id="txtNombre"  value="#{usuarioController.usuarioValidado.idinvestigador.nombre}" 
                                       required="true" style="background-color: #FBDCDC ;"
                                             /></td>
                      
                      
                      <td style="font-weight: bold; size: 25px; color: blue;" align="right">#{props['inv.lbl.apellidos']}: </td>
                      <td><p:inputText id="txtApellidos"  value="#{usuarioController.usuarioValidado.idinvestigador.apellidos}" 
                                       required="true" style="background-color: #FBDCDC;"
                                            /></td>
                     
                    </tr>
                      
                    <tr>
                        <td style="font-weight: bold; size: 25px; color: blue;" align="right">#{props['inv.lbl.edad']}: </td>
                      <td style="width: 10px;"><p:spinner id="txtEdad" value="#{usuarioController.usuarioValidado.idinvestigador.edad}" min="20" max="70" 
                                     required="true" style="background-color: #FBDCDC;"
                                              /></td>
                     
                        
                        <td style="font-weight: bold; size: 25px; color: blue;" align="right">#{props['inv.lbl.telefonof']}: </td>
                      <td><p:inputMask id="txtTelefono"  value="#{usuarioController.usuarioValidado.idinvestigador.telefonofijo}" 
                                       required="true" style="background-color: #FBDCDC;"
                                             mask="(999) 999-9999"/></td>                  
                      
                    </tr>  
                      
                    <tr>
                       <td style="font-weight: bold; size: 12px; color: blue;" align="right">#{props['inv.lbl.programa']}: </td>
                       <td><p:selectOneMenu id="txtIdPrograma" value="#{usuarioController.usuarioValidado.idinvestigador.idprograma}"  required="true" 
                                             disabled="true">
                              <f:selectItems value="#{programaController.itemsAvailableSelectOne}"/>
                           </p:selectOneMenu></td>
                        
                        
                        <td style="font-weight: bold; size: 25px; color: blue;" align="right">#{props['inv.lbl.telefonoc']}: </td>
                       <td><p:inputMask id="txtTelefonoCelular"  value="#{usuarioController.usuarioValidado.idinvestigador.telefonocelular}" 
                                       required="true" style="background-color: #FBDCDC;"
                                             mask="(999) 999-9999"/></td>
                       
                     </tr>  
                    
                     <tr>
                         <td style="font-weight: bold; size: 25px; color: blue;" align="right">#{props['inv.lbl.correo']} : </td>
                        <td> <p:inputText id="txtEmail"  required="true" style="background-color: #FBDCDC;"
                                     
                                    validatorMessage="#{props['usu.lbl.usuarioinvalido']}"
                                    value="#{usuarioController.usuarioValidado.idinvestigador.correo}" >
                           <f:validateRegex pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$" />
                           </p:inputText> </td>
                         
                      
                         <td style="font-weight: bold; size: 25px; color: blue;" align="right">#{props['inv.lbl.direccion']} : </td>
                         <td><p:inputText id="txtDireccion"  value="#{usuarioController.usuarioValidado.idinvestigador.direccion}" 
                                       required="true" style="background-color: #FBDCDC;"
                                             requiredMessage="#{props['admin.required.idUsuario']}"/></td>
                         <td><p:message for="txtDireccion"/></td>
                    </tr>
                    
                    <tr>
                        <td style="font-weight: bold; size: 25px; color: blue;" align="right">#{props['inv.lbl.principal']} : </td>
                           <td><p:selectOneRadio id="txtPrincipal" value="#{usuarioController.usuarioValidado.idinvestigador.principal}"
                                                 required="true" 
                                                  disabled="true">
                                    <f:selectItem itemLabel="#{props['usu.lbl.si']}" itemValue="1" />
                                    <f:selectItem itemLabel="#{props['usu.lbl.no']}" itemValue="0" />
                               </p:selectOneRadio></td>
                           
                    
                        <td style="font-weight: bold; size: 25px; color: blue;" align="right">#{props['inv.lbl.rol']} : </td>
                           <td><p:inputText id="txtRol"  value="#{usuarioController.usuarioValidado.idinvestigador.rol}" 
                                       required="true" style="background-color: #FBDCDC;"
                                             /></td>
                           
                      </tr>
                      
                      <tr>
                          <td style="font-weight: bold; size: 12px; color: blue;" align="right">#{props['inv.lbl.tipoVin']}</td>
                           <td> 
                                <p:selectOneMenu id="txtRoles" value="#{usuarioController.usuarioValidado.idinvestigador.tipovinculacion}"  
                                                 disabled="true">
                                    <f:selectItem itemLabel="#{props['usu.lbl.selecciontipovin']}" itemValue="" />
                                    <f:selectItem itemLabel="#{props['usu.lbl.propiedad']}" itemValue="Propiedad" />
                                    <f:selectItem itemLabel="#{props['usu.lbl.provisional']}" itemValue="Provisional"   />
                                    <f:selectItem itemLabel="#{props['usu.lbl.catedratico']}" itemValue="Catedratico"  />
                                   
                                </p:selectOneMenu>
                           </td>
                           
    
                          <td style="font-weight: bold; size: 12px; color: blue;" align="right">#{props['inv.lbl.grupoInv']}: </td>
                           <td><p:selectOneMenu id="txtIdGrupoInv" value="#{usuarioController.usuarioValidado.idinvestigador.idgrupoinv}" 
                                               required="true" disabled="true"
                                                  >
                                  <f:selectItems value="#{grupoinvestigacionController.itemsAvailableSelectOne}"/>
                                </p:selectOneMenu></td>
                           
                      </tr>
   
                      
                  </table>
               </center>
               <center>
                  <table>
                      <tr>   
                         <td colspan="2">
                             <center><p:commandButton value="#{props['admin.btn.actualizar']}" action="#{usuarioController.editarInv()}" update="@form"/></center> 
                          </td>
                       </tr>
                       <tr>
                              <td colspan="3" style="text-align: center; color: red; font-weight: bold;">
                                  <p:outputLabel value="#{investigadorController.mensaje}"/>
                               </td>
                       </tr>

                    </table>
                </center>
         </h:form>
      </p:panel>
       
     
        <p:panel id="curriculum" header="#{props['inv.lbl.hojavida']}"  style="margin-bottom:20px; width: 85%; margin-left: 7%; margin-top: 30px;" >   
                    <p:commandButton value="#{props['inv.lbl.cargar']}" type="button" onclick="PF('curriculum').show();" />      
                    <p:outputLabel value="#{usuarioController.usuarioValidado.idinvestigador.curriculumruta}"/>
                   <p:outputLabel value="#{usuarioController.mensajecargarM}"/>
                    <p:dialog header="#{props['inv.lbl.cargarcurriculum']}" widgetVar="curriculum" minHeight="40" width="500">
                        <p:panel>  
                           <h:form enctype="multipart/form-data">

                               <p:fileUpload value="#{usuarioController.file}" mode="simple"/>
                               <p:commandButton value="#{props['inv.lbl.cargar']}" ajax="false" actionListener="#{usuarioController.uploadInv()}" />
                               
                           </h:form>
                        </p:panel>
                    </p:dialog>  
                </p:panel> 
        
                <p:panel id="titulo" header="#{props['inv.lbl.ingresartitul']}"  style="margin-bottom:20px; width: 85%; margin-left: 7%; margin-top: 30px;" >   
                    <p:commandButton value="#{props['inv.lbl.cargar']}" type="button" onclick="PF('tituloInv').show();"  />      
                    <p:outputLabel value="#{usuarioController.misTitulos()}"/>
                    <p:dialog header="#{props['inv.lbl.cargartitulos']}" widgetVar="tituloInv" minHeight="40" width="900" >
                    <p:ajax event="close"  listener="#{usuarioController.refrescar()}"/>    
                        <p:panel>  
                           <ui:include src="/investigador/cargarTitulo.xhtml" />
                        </p:panel>
                    </p:dialog>  
                </p:panel>   
           
    </ui:define>

</ui:composition>


web/investigador/proyectoInfoBasica.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../WEB-INF/TemplateSV.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui">
    
  
  <p:panel style="margin-bottom:5px; width: 99%;  margin-top: 5px;" > 
     <div style="height: 15px;"></div>  
     
       <p:growl id="msgs" showDetail="true" />
        <center>     
        <p:focus for="txtIdProyecto"/>
        <table>
           <tr style="margin-top: 8px;">
               <td style="color: blue; width: 23%; font-weight: bold; size: 25px;" align="right" >#{props['usu.lbl.idproyecto']} : </td>
               <td style="width: 23%;"><p:inputText id="txtIdProyecto"  value="#{usuarioController.proyectoController.selected.idproyecto}" 
                                                                 required="true" style="background-color: #FBDCDC;" maxlength="10" disabled="#{usuarioController.id}"/></td>
               <td style="width: 5%;"></td>                    
               <td style="color: blue; width: 23%; font-weight: bold; size: 25px;" align="right">#{props['inv.lbl.grupoInv']}: </td>
               <td style="width: 23%;"><p:inputText id="txtNombre"  value="#{usuarioController.usuarioValidado.idinvestigador.idgrupoinv.nombre}" 
                                   required="true" style="background-color: #FBDCDC; " disabled="true"/></td>
          </tr>
        </table>
        <table align="center">
           <tr style="margin-top: 8px;">
               <td style="color: blue; width: 23%; font-weight: bold; size: 25px;" align="right" >#{props['usu.lbl.fechapublic']} : </td>
               <td style="width: 23%; "><p:calendar id="txtIdFecha"  value="#{usuarioController.proyectoController.selected.fecha}" 
                                   required="true" style="background-color: #FBDCDC;" disabled="#{usuarioController.proyectoController.panel2}"/></td>
               <td style="width: 8%;"></td>                    
               <td style="font-weight: bold; width: 23%; size: 12px; color: blue; width: 23%;" align="right">#{props['usu.lbl.convocatoria']}: </td>
               <td style="width: 23%;"><p:selectOneMenu id="txtIdConvocatoria" value="#{usuarioController.proyectoController.convocatoria}"  
                                    required="true" style="width: 100%;" disabled="#{usuarioController.proyectoController.panel2}">
                              <f:selectItems value="#{convocatoriaController.itemsAvailableSelectOne}"/>
                           </p:selectOneMenu></td>
          </tr>
        </table>
        <table>
          <tr style="margin-top: 8px;">
               <td style="font-weight: bold; size: 25px; color: blue; width: 25%;" align="right">#{props['usu.lbl.tituloproyecto']}: </td>
               <td style="width: 75%;"><p:inputTextarea id="txtTitulo"  value="#{usuarioController.proyectoController.selected.titulo}" 
                                                        required="true" style="background-color: white; width: 100%;" maxlength="500" disabled="#{usuarioController.proyectoController.panel2}"/></td>
          </tr>
        </table>
        <table>
            <tr style="margin-top: 8px;"> 
              <td style="font-weight: bold; size: 25px; color: blue; width: 23%;" align="right">#{props['usu.lbl.lineadeinv']}: </td>
              <td style="width: 23%; "><p:inputText id="txtLineaInv"  value="#{usuarioController.proyectoController.selected.lineainves}" 
                                                     required="true" style="background-color: #FBDCDC;" maxlength="100"
                                                     disabled="#{usuarioController.proyectoController.panel2}"/></td> 
               <td style="width: 8%;"></td>   
               <td style="font-weight: bold; size: 25px; color: blue;width: 23%;" align="right">#{props['usu.lbl.totalinv']}: </td>
               <td style="width: 30px;"><p:spinner id="txtCantidadInv" value="#{usuarioController.proyectoController.selected.totalinves}" 
                                                   min="1" max="50" required="true" style="background-color: #FBDCDC;"
                                                   disabled="#{usuarioController.proyectoController.panel2}"/></td>                
            </tr>  
            
            <tr style="margin-top: 8px;"> 
              <td style="font-weight: bold; size: 25px; color: blue; width: 23%;" align="right">#{props['usu.lbl.entidad']}: </td>
              <td style="width: 23%; "><p:inputText id="txtEntidad"  value="#{usuarioController.proyectoController.selected.entidad}" 
                                                     required="true" style="background-color: #FBDCDC;" maxlength="100"
                                                     disabled="#{usuarioController.proyectoController.panel2}"/></td> 
               <td style="width: 8%;"></td>   
               <td style="font-weight: bold; size: 25px; color: blue;width: 23%;" align="right">#{props['usu.lbl.lugarejecucion']}: </td>
               <td style="width: 23%;"><p:inputText id="txtLugarEjec" value="#{usuarioController.proyectoController.selected.lugarejecucion}" 
                                                  required="true" style="background-color: #FBDCDC;" maxlength="100"
                                                  disabled="#{usuarioController.proyectoController.panel2}"/></td>                
            </tr>  
                 
            
            <tr style="margin-top: 8px;"> 
              <td style="font-weight: bold; size: 25px; color: blue; width: 23%;" align="right">#{props['usu.lbl.ciudad']}: </td>
              <td style="width: 23%; "><p:inputText id="txtCiudad"  value="#{usuarioController.proyectoController.selected.ciudad}" 
                                                     required="true" style="background-color: #FBDCDC;" maxlength="100"
                                                     disabled="#{usuarioController.proyectoController.panel2}"/></td> 
               <td style="width: 8%;"></td>   
               <td style="font-weight: bold; size: 25px; color: blue;width: 23%;" align="right">#{props['usu.lbl.tiempomeses']}: </td>
               <td style="width: 30px;"><p:spinner id="txtDuracionMeses" value="#{usuarioController.proyectoController.selected.duracionmeses}" 
                                                   min="1" max="60" required="true" style="background-color: #FBDCDC;"
                                                   disabled="#{usuarioController.proyectoController.panel2}"/></td>                
            </tr>
            
            <tr style="margin-top: 8px;"> 
               <td style="font-weight: bold; size: 25px; color: blue; width: 23%;" align="right">#{props['usu.lbl.tipoproyecto']}: </td>
               <td style="width: 23%; "><p:inputText id="txtTipo"  value="#{usuarioController.proyectoController.selected.tipoproyecto}" 
                                                     required="true" style="background-color: #FBDCDC;" maxlength="100"
                                                     disabled="#{usuarioController.proyectoController.panel2}"/></td> 
               <td style="width: 8%;"></td>   
               <td style="font-weight: bold; size: 25px; color: blue; width: 23%;" align="right">#{props['usu.lbl.modalidad']}: </td>
               <td style="width: 23%; "><p:inputText id="txtModalidad"  value="#{usuarioController.proyectoController.selected.modalidad}" 
                                                     required="true" style="background-color: #FBDCDC;" maxlength="100"
                                                     disabled="#{usuarioController.proyectoController.panel2}"/></td>               
            </tr>
         </table>
        <div style="height: 15px; "></div> 
        <table style="margin-top: 8px;">
             <p:commandButton value="#{props['admin.btn.crear']}" action="#{usuarioController.guardarProyecto()}" disabled="#{usuarioController.proyectoController.botonGurdar}" update="@form"/> 
             <p:commandButton value="#{props['admin.btn.actualizar']}" action="#{usuarioController.actualizarProyecto()}" disabled="#{usuarioController.proyectoController.paneles}" update="@form"/>
             <p:commandButton value="#{props['admin.btn.guardarCambios']}" action="#{usuarioController.editarProyecto()}" disabled="#{usuarioController.proyectoController.editar}" update="@form"/>
       
        </table>
        <table>
          <tr>
             <td colspan="3" style="text-align: center; color: red; font-weight: bold;">
                 <p:outputLabel value="#{usuarioController.proyectoController.mensaje}"/>
             </td>
          </tr>
        </table>
      </center>
        
   
             
             
             
         
         </p:panel>    
 
</html>